# -*- coding: utf-8 -*-
"""Exp1 extension

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XACOFf13NEDRa79oAiyhKdTsbDxiG1c5
"""

import numpy as np
import matplotlib.pyplot as plt


class PlottingPerceptron:
    #single layer perceptron
    def __init__(self, learning_rate=0.1, epochs=10):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None

    #activation function
    def _step_activation(self, z):
        return np.where(z >= 0, 1, 0)

    def fit_and_plot(self, X, y, gate_name="Logic  gate"):
        num_samples, num_features = X.shape
        #initialise weights and bias to 0
        self.weights = np.zeros(num_features)
        self.bias = 0.0

        step_counter = 0

        print(f" Initial Weights: {self.weights}, Initial Bias: {self.bias}")

        #Initial state
        self._plot_state(X, y, gate_name, step_counter, sample_idx=None, updated=False)

        for epoch in range(1, self.epochs + 1):
            total_errors = 0

            for idx in range(num_samples):
                x_i = X[idx]
                target = y[idx]

                #wTx+b formula
                z = np.dot(x_i, self.weights) + self.bias
                prediction = self._step_activation(z)

                error = target-prediction

                if error != 0:
                    total_errors += 1
                    step_counter += 1

                    #updation
                    self.weights += self.lr * error * x_i
                    self.bias += self.lr * error

                    print(f"Epoch {epoch} | Sample {idx} (X={x_i}, y={target}) | "
                          f"Predicted={prediction} | Misclassified :"
                          f"Updated Weights: {np.round(self.weights, 2)}, Bias: {round(self.bias, 2)}")
                else:
                    print(f"Epoch {epoch} | Sample {idx} (X={x_i}, y={target}) | "
                          f"Predicted={prediction} | Correct so no update")

            if total_errors == 0:
                print(f"\nConverged successfully at Epoch {epoch}\n")

                self._plot_state(X, y, gate_name, step_counter, sample_idx=None,
                                  updated=True, final=True)
                break

            #one plot per epoch
            self._plot_state(X, y, gate_name, step_counter, sample_idx=None, updated=True)

    def _plot_state(self, X, y, gate_name, step, sample_idx, updated, final=False):
        num_features = X.shape[1]


        plot_bias = self.bias
        if final:
            z_vals = X.dot(self.weights) + self.bias
            z0 = z_vals[y == 0]
            z1 = z_vals[y == 1]
            if len(z0) > 0 and len(z1) > 0:
                margin_center = (z0.max() + z1.min()) / 2
                plot_bias = self.bias - margin_center

        if num_features == 1:
            #not gate visual
            fig, ax = plt.subplots(figsize=(6, 3))

            #1d plot
            for class_val, color, marker in zip([0, 1], ['red', 'blue'], ['o', 's']):
                mask = (y == class_val)
                ax.scatter(X[mask], np.zeros(np.sum(mask)), color=color,
                           s=120, label=f"Class {class_val}", zorder=3)

            #boundary
            if self.weights[0] != 0:
                boundary_x = -plot_bias / self.weights[0]
                ax.axvline(x=boundary_x, color='black', linestyle='--', linewidth=2, label="Decision Boundary")

            ax.set_ylim(-0.5, 0.5)
            ax.set_yticks([])
            ax.set_xlabel("X1")

        elif num_features == 2:
            #2d visualisation
            fig, ax = plt.subplots(figsize=(6, 5))

            #data points
            for class_val, color, marker in zip([0, 1], ['red', 'blue'], ['o', 's']):
                mask = (y == class_val)
                ax.scatter(X[mask, 0], X[mask, 1], color=color, marker=marker,
                           s=120, label=f"Class {class_val}", zorder=3)

            if sample_idx is not None:
                ax.scatter(X[sample_idx, 0], X[sample_idx, 1], s=250,
                           facecolors='none', edgecolors='green', linewidths=2.5,
                           label="Misclassified Sample", zorder=4)

            x1_vals = np.array([-0.5, 1.5])
            if self.weights[1] != 0:
                x2_vals = -(self.weights[0] * x1_vals + plot_bias) / self.weights[1]
                ax.plot(x1_vals, x2_vals, color='black', linestyle='--', linewidth=2, label="Decision Boundary")
            elif self.weights[0] != 0:
                # Vertical decision boundary
                x1_boundary = -plot_bias / self.weights[0]
                ax.axvline(x=x1_boundary, color='black', linestyle='--', linewidth=2, label="Decision Boundary")

            ax.set_xlim(-0.5, 1.5)
            ax.set_ylim(-0.5, 1.5)
            ax.set_xlabel("X1")
            ax.set_ylabel("X2")
            ax.grid(True, alpha=0.3)

        title = f"{gate_name} | Step {step}"
        if final:
            title += " (Converged / Final Boundary)"
        if updated:
            title += f"\nWeights: {np.round(self.weights, 2)}, Bias: {round(self.bias, 2)}"
        else:
            title += " (Initial State)"

        plt.title(title, fontsize=10)
        plt.legend(loc="upper right", fontsize=8)
        plt.tight_layout()
        plt.show()


#data for or, and, not gate
X_or = np.array([[0,0], [0,1], [1,0], [1,1]])
y_or = np.array([0,1,1,1])

X_and = np.array([[0,0], [0,1], [1,0], [1,1]])
y_and = np.array([0,0,0,1])

X_not = np.array([[0],[1]])
y_not = np.array([1,0])

#Train on Or, And, Not gate
p_or = PlottingPerceptron(learning_rate=0.1, epochs=10)
p_or.fit_and_plot(X_or, y_or, gate_name="OR GATE")

p_and = PlottingPerceptron(learning_rate=0.1, epochs=10)
p_and.fit_and_plot(X_and, y_and, gate_name="AND GATE")

p_not = PlottingPerceptron(learning_rate=0.1, epochs=10)
p_not.fit_and_plot(X_not, y_not, gate_name="NOT GATE")