# -*- coding: utf-8 -*-
"""exp2_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mcb9b0rwURPhoqUvEX4IgJo3ZaDpEtfr
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

# TensorFlow & Keras
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.utils import to_categorical

# Scikit-learn & SciKeras
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_recall_fscore_support
from sklearn.model_selection import RandomizedSearchCV
from scikeras.wrappers import KerasClassifier

# Set random seed for reproducibility
np.random.seed(42)
tf.random.set_seed(42)


#Preprocessing
print("--- Loading and Preprocessing Dataset ---")
# 1. Load Fashion-MNIST
fashion_mnist = tf.keras.datasets.fashion_mnist
(X_train_raw, y_train_raw), (X_test_raw, y_test_raw) = fashion_mnist.load_data()

class_names = [
    'T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
    'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot'
]

# Print raw dimensions
print(f"Raw Training Data Shape: {X_train_raw.shape}")
print(f"Raw Testing Data Shape: {X_test_raw.shape}")

#images
plt.figure(figsize=(10, 5))
for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(X_train_raw[i], cmap='gray')
    plt.title(class_names[y_train_raw[i]], fontsize=9)
    plt.axis('off')
plt.suptitle("Plot 1: 10 Sample Images from Fashion-MNIST", fontsize=14)
plt.tight_layout()
plt.savefig("plot1_sample_images.png")
plt.show()

#class dist
plt.figure(figsize=(10, 4))
unique, counts = np.unique(y_train_raw, return_counts=True)
sns.barplot(x=[class_names[u] for u in unique], y=counts, palette="viridis")
plt.title("Plot 2: Class Distribution in Training Set")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("plot2_class_distribution.png")
plt.show()

# 2. Preprocess: Flattening and Normalizing
# Reshape from (28, 28) to 784-dimensional vector and convert to float32
X_train = X_train_raw.reshape(-1, 28 * 28).astype('float32') / 255.0
X_test = X_test_raw.reshape(-1, 28 * 28).astype('float32') / 255.0

# Convert labels into one-hot vectors
y_train = to_categorical(y_train_raw, num_classes=10)
y_test = to_categorical(y_test_raw, num_classes=10)

print(f"Preprocessed Training Data Shape: {X_train.shape}")
print(f"Preprocessed Testing Data Shape: {X_test.shape}")


# ==========================================
# TASK 3 & 4: BASELINE MODEL CONSTRUCTION & TRAINING
# ==========================================
print("\n--- Constructing and Training Baseline Model ---")

def build_baseline_model():
    model = Sequential([
        Input(shape=(784,)),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(10, activation='softmax')
    ])
    return model

baseline_model = build_baseline_model()
baseline_model.summary()

baseline_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

start_time = time.time()
baseline_history = baseline_model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)
baseline_train_time = time.time() - start_time


#Evaluation
print("\n--- Evaluating Baseline Model ---")
baseline_loss, baseline_accuracy = baseline_model.evaluate(X_test, y_test, verbose=0)
y_pred_baseline = baseline_model.predict(X_test)
y_pred_baseline_classes = np.argmax(y_pred_baseline, axis=1)

print(f"Baseline Test Accuracy: {baseline_accuracy:.4f}")
print("\nBaseline Classification Report:")
print(classification_report(y_test_raw, y_pred_baseline_classes, target_names=class_names))

#Metrics
b_prec, b_rec, b_f1, _ = precision_recall_fscore_support(y_test_raw, y_pred_baseline_classes, average='macro')


#Hyperparameter
print("\n--- Running Automated Hyperparameter Optimization ---")

# Define flexible build function for SciKeras Wrapper
def create_clf_model(hidden_layers=1, hidden_neurons=128, learning_rate=0.001,
                     optimizer='Adam', activation_function='relu', dropout_rate=0.0):
    model = Sequential()
    model.add(Input(shape=(784,)))

    # Dynamic hidden layers
    for i in range(hidden_layers):
        model.add(Dense(hidden_neurons, activation=activation_function.lower()))
        if dropout_rate > 0.0:
            model.add(Dropout(dropout_rate))

    model.add(Dense(10, activation='softmax'))

    # Handle optimizer instances with appropriate learning rates
    if optimizer.lower() == 'adam':
        opt = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    elif optimizer.lower() == 'sgd':
        opt = tf.keras.optimizers.SGD(learning_rate=learning_rate)
    elif optimizer.lower() == 'rmsprop':
        opt = tf.keras.optimizers.RMSprop(learning_rate=learning_rate)
    else:
        opt = 'adam'

    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Wrap the model using KerasClassifier
wrapped_model = KerasClassifier(
    model=create_clf_model,
    epochs=10,
    batch_size=32,
    verbose=0
)

#Search space
param_dist = {
    'model__hidden_layers': [1, 2],
    'model__hidden_neurons': [64, 128, 256],
    'model__learning_rate': [0.01, 0.001],
    'batch_size': [32, 64],
    'epochs': [10, 20],
    'model__optimizer': ['Adam', 'SGD'],
    'model__activation_function': ['ReLU', 'Tanh'],
    'model__dropout_rate': [0.0, 0.2]
}

random_search = RandomizedSearchCV(
    estimator=wrapped_model,
    param_distributions=param_dist,
    n_iter=5,
    cv=3,
    scoring='accuracy',
    verbose=1,
    random_state=42,
    n_jobs=1
)

# Fit Randomized Search on a subset to keep execution time practical
print("Fitting Randomized Search (this may take a few minutes)...")
random_search.fit(X_train[:10000], y_train[:10000]) # Using 10,000 samples for time-efficiency

print(f"\nBest Cross-Validation Score: {random_search.best_score_:.4f}")
print("Best Hyperparameters Found:")
for param, val in random_search.best_params_.items():
    print(f"  {param}: {val}")


#Retrain
print("\n--- Retraining Best Model on Full Dataset ---")
best_params = random_search.best_params_

optimized_model = create_clf_model(
    hidden_layers=best_params['model__hidden_layers'],
    hidden_neurons=best_params['model__hidden_neurons'],
    learning_rate=best_params['model__learning_rate'],
    optimizer=best_params['model__optimizer'],
    activation_function=best_params['model__activation_function'],
    dropout_rate=best_params['model__dropout_rate']
)

# Train best model
start_time = time.time()
opt_history = optimized_model.fit(
    X_train, y_train,
    epochs=best_params['epochs'],
    batch_size=best_params['batch_size'],
    validation_split=0.2,
    verbose=1
)
opt_train_time = time.time() - start_time


print("\n--- Evaluating Optimized Model ---")
opt_loss, opt_accuracy = optimized_model.evaluate(X_test, y_test, verbose=0)
y_pred_opt = optimized_model.predict(X_test)
y_pred_opt_classes = np.argmax(y_pred_opt, axis=1)

print(f"Optimized Test Accuracy: {opt_accuracy:.4f}")
print("\nOptimized Classification Report:")
print(classification_report(y_test_raw, y_pred_opt_classes, target_names=class_names))

o_prec, o_rec, o_f1, _ = precision_recall_fscore_support(y_test_raw, y_pred_opt_classes, average='macro')



print("\n--- Generating Plots ---")

# Plots 3 & 4: Training & Validation Accuracy vs Epoch
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(baseline_history.history['accuracy'], label='Baseline Train Acc', color='blue')
plt.plot(baseline_history.history['val_accuracy'], label='Baseline Val Acc', color='blue', linestyle='--')
plt.plot(opt_history.history['accuracy'], label='Opt Train Acc', color='green')
plt.plot(opt_history.history['val_accuracy'], label='Opt Val Acc', color='green', linestyle='--')
plt.title("Plots 3 & 4: Accuracy vs Epoch")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()


plt.subplot(1, 2, 2)
plt.plot(baseline_history.history['loss'], label='Baseline Train Loss', color='blue')
plt.plot(baseline_history.history['val_loss'], label='Baseline Val Loss', color='blue', linestyle='--')
plt.plot(opt_history.history['loss'], label='Opt Train Loss', color='green')
plt.plot(opt_history.history['val_loss'], label='Opt Val Loss', color='green', linestyle='--')
plt.title("Plots 5 & 6: Loss vs Epoch")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.tight_layout()
plt.savefig("plot3_to_6_learning_curves.png")
plt.show()


plt.figure(figsize=(8, 7))
cm = confusion_matrix(y_test_raw, y_pred_opt_classes)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title("Plot 7: Confusion Matrix (Optimized Model)")
plt.xlabel("Predicted Labels")
plt.ylabel("True Labels")
plt.tight_layout()
plt.savefig("plot7_confusion_matrix.png")
plt.show()


plt.figure(figsize=(10, 4))
cv_results = random_search.cv_results_
mean_scores = cv_results['mean_test_score']
params_labels = [f"Iter {i+1}" for i in range(len(mean_scores))]
plt.bar(params_labels, mean_scores, color='salmon', edgecolor='black')
plt.ylim(0, 1.0)
plt.title("Plot 8: Hyperparameter Search Iterations Accuracy")
plt.xlabel("Search Configuration")
plt.ylabel("Mean CV Accuracy Score")
for i, score in enumerate(mean_scores):
    plt.text(i, score + 0.02, f"{score:.3f}", ha='center', fontweight='bold')
plt.tight_layout()
plt.savefig("plot8_hyperparameter_search.png")
plt.show()

# Plot 9: Best Model Accuracy Comparison
plt.figure(figsize=(6, 5))
models_comparison = ['Baseline', 'Optimized']
accuracies = [baseline_accuracy, opt_accuracy]
sns.barplot(x=models_comparison, y=accuracies, palette="muted")
plt.title("Plot 9: Best Model Accuracy Comparison")
plt.ylabel("Testing Accuracy")
plt.ylim(0, 1.0)
for i, score in enumerate(accuracies):
    plt.text(i, score + 0.02, f"{score:.4f}", ha='center', fontweight='bold')
plt.savefig("plot9_accuracy_comparison.png")
plt.show()


#Tables
print("\n" + "="*50)
print("FINAL RESULTS TABLE")
print("="*50)
print(f"Best CV Score (during search): {random_search.best_score_:.4f}")
print(f"Optimized Test Accuracy:      {opt_accuracy:.4f}\n")

print(f"{'Metric':<15} | {'Baseline':<12} | {'Optimized':<12}")
print("-" * 45)
print(f"{'Accuracy':<15} | {baseline_accuracy:<12.4f} | {opt_accuracy:<12.4f}")
print(f"{'Precision':<15} | {b_prec:<12.4f} | {o_prec:<12.4f}")
print(f"{'Recall':<15} | {b_rec:<12.4f} | {o_rec:<12.4f}")
print(f"{'F1-score':<15} | {b_f1:<12.4f} | {o_f1:<12.4f}")
print(f"{'Training Time':<15} | {f'{baseline_train_time:.2f}s':<12} | {f'{opt_train_time:.2f}s':<12}")
print("="*50)

!pip install scikeras