# -*- coding: utf-8 -*-
"""exp2 _extension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IdjhaqYoTyRHFcTkOFRf7oJgN51wlEQV
"""

import numpy as np
import matplotlib.pyplot as plt


class MultiLayerPerceptron:
    #2 layer mlp
    def __init__(self, num_inputs=2, num_hidden=4, learning_rate=0.5, epochs=5000, seed=42):
        rng = np.random.default_rng(seed)
        self.lr = learning_rate
        self.epochs = epochs

        #init
        self.W1 = rng.uniform(-1, 1, size=(num_inputs, num_hidden))
        self.b1 = np.zeros(num_hidden)
        self.W2 = rng.uniform(-1, 1, size=(num_hidden, 1))
        self.b2 = np.zeros(1)

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def _sigmoid_derivative(self, a):
        return a * (1 - a)

    def _forward(self, X):
        z1 = X.dot(self.W1) + self.b1
        a1 = self._sigmoid(z1)
        z2 = a1.dot(self.W2) + self.b2
        a2 = self._sigmoid(z2)
        return a1, a2

    def fit_and_plot(self, X, y, gate_name="XOR GATE", print_every=500,
                      plot_epochs=(0, 1, 50, 200, 1000, 5000)):
        y_col = y.reshape(-1, 1)
        loss_history = []
        plot_epochs = set(plot_epochs)

        #initial state, before any training
        self._plot_state(X, y, gate_name, epoch=0)

        for epoch in range(1, self.epochs + 1):
            #forward pass
            a1, a2 = self._forward(X)

            #mean squared error loss
            loss = np.mean((y_col - a2) ** 2)
            loss_history.append(loss)

            #backward pass
            error_output = (a2 - y_col) * self._sigmoid_derivative(a2)
            grad_W2 = a1.T.dot(error_output)
            grad_b2 = error_output.sum(axis=0)

            error_hidden = error_output.dot(self.W2.T) * self._sigmoid_derivative(a1)
            grad_W1 = X.T.dot(error_hidden)
            grad_b1 = error_hidden.sum(axis=0)

            #gradient descent update
            self.W2 -= self.lr * grad_W2
            self.b2 -= self.lr * grad_b2
            self.W1 -= self.lr * grad_W1
            self.b1 -= self.lr * grad_b1

            if epoch % print_every == 0 or epoch == 1:
                preds = (a2 >= 0.5).astype(int).flatten()
                print(f"Epoch {epoch:5d} | Loss: {loss:.5f} | Predictions: {preds} | Target: {y}")

            if epoch in plot_epochs:
                self._plot_state(X, y, gate_name, epoch=epoch)

        final_preds = self.predict(X)
        print(f"\nFinal predictions: {final_preds}")
        print(f"Target labels:     {y}")
        print(f"Accuracy: {np.mean(final_preds == y) * 100:.1f}%")

        self._plot_loss(loss_history)

    def predict(self, X):
        _, a2 = self._forward(X)
        return (a2 >= 0.5).astype(int).flatten()

    def _plot_state(self, X, y, gate_name, epoch):
        fig, ax = plt.subplots(figsize=(6, 5))

        for class_val, color, marker in zip([0, 1], ['red', 'blue'], ['o', 's']):
            mask = (y == class_val)
            ax.scatter(X[mask, 0], X[mask, 1], color=color, marker=marker,
                       s=120, label=f"Class {class_val}", zorder=3)

        #boundary curve where predicted probability = 0.5
        x1_vals = np.linspace(-0.5, 1.5, 300)
        x2_vals = np.linspace(-0.5, 1.5, 300)
        xx1, xx2 = np.meshgrid(x1_vals, x2_vals)
        grid = np.c_[xx1.ravel(), xx2.ravel()]
        _, probs = self._forward(grid)
        probs = probs.reshape(xx1.shape)

        ax.contour(xx1, xx2, probs, levels=[0.5], colors='black',
                   linestyles='--', linewidths=2)
        ax.plot([], [], color='black', linestyle='--', linewidth=2, label="Decision Boundary")

        ax.set_xlim(-0.5, 1.5)
        ax.set_ylim(-0.5, 1.5)
        ax.set_xlabel("X1")
        ax.set_ylabel("X2")
        ax.grid(True, alpha=0.3)

        title = f"{gate_name} (MLP) | Epoch {epoch}"
        if epoch == 0:
            title += " (Initial State)"

        plt.title(title, fontsize=10)
        plt.legend(loc="upper right", fontsize=8)
        plt.tight_layout()
        plt.show()

    def _plot_loss(self, loss_history):
        fig, ax = plt.subplots(figsize=(6, 4))
        ax.plot(loss_history, color='navy')
        ax.set_xlabel("Epoch")
        ax.set_ylabel("Mean Squared Error")
        ax.set_title("XOR Gate - Training Loss Curve", fontsize=10)
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()


#data for xor gate
X_xor = np.array([[0,0],[0,1],[1,0],[1,1]])
y_xor = np.array([0,1,1,0])

#Train on Xor gate
mlp_xor = MultiLayerPerceptron(num_inputs=2, num_hidden=4, learning_rate=0.5, epochs=5000)
mlp_xor.fit_and_plot(X_xor, y_xor, gate_name="XOR GATE")