# -*- coding: utf-8 -*-
"""DLlab6_modified_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykJiNqfaDI9kC5A58IyDVl22nUfK_4IK
"""

import os, time, zipfile, io, glob, random, urllib.request
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, Input
from sklearn.metrics import (
                              confusion_matrix, ConfusionMatrixDisplay)
from sklearn.model_selection import train_test_split

SEED = 42
random.seed(SEED); np.random.seed(SEED); tf.random.set_seed(SEED)

print("TF version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

DATA_DIR = "/content/UCI_HAR"
ZIP_URL = "https://archive.ics.uci.edu/static/public/240/human+activity+recognition+using+smartphones.zip"
ZIP_PATH = "/content/har.zip"

if not os.path.exists(DATA_DIR):
    print("Downloading UCI HAR dataset...")
    urllib.request.urlretrieve(ZIP_URL, ZIP_PATH)
    with zipfile.ZipFile(ZIP_PATH, 'r') as z:
        z.extractall("/content/UCI_HAR_outer")

    inner_zip = glob.glob("/content/UCI_HAR_outer/**/*.zip", recursive=True)
    if inner_zip:
        with zipfile.ZipFile(inner_zip[0], 'r') as z:
            z.extractall(DATA_DIR)
    else:
        DATA_DIR = "/content/UCI_HAR_outer"
    print("Done.")
else:
    print("Already downloaded.")


def find_har_root(base):
    for root, dirs, files in os.walk(base):
        if 'train' in dirs and 'test' in dirs:
            return root
    raise FileNotFoundError("Could not locate UCI HAR Dataset root — inspect the extracted folder manually.")

HAR_ROOT = find_har_root(DATA_DIR)
print("HAR root:", HAR_ROOT)

SIGNALS = [
    "body_acc_x", "body_acc_y", "body_acc_z",
    "body_gyro_x", "body_gyro_y", "body_gyro_z",
    "total_acc_x", "total_acc_y", "total_acc_z",
]

def load_signals(subset):

    signal_dir = os.path.join(HAR_ROOT, subset, "Inertial Signals")
    data = []
    for sig in SIGNALS:
        fname = os.path.join(signal_dir, f"{sig}_{subset}.txt")
        arr = np.loadtxt(fname)
        data.append(arr)
    X = np.stack(data, axis=-1)
    return X.astype(np.float32)

def load_labels(subset):
    fname = os.path.join(HAR_ROOT, subset, f"y_{subset}.txt")
    y = np.loadtxt(fname).astype(int) - 1
    return y

X_train_full = load_signals("train")
y_train_full = load_labels("train")
X_test_full  = load_signals("test")
y_test_full  = load_labels("test")

ACTIVITIES = ["WALKING", "WALKING_UPSTAIRS", "WALKING_DOWNSTAIRS", "SITTING", "STANDING", "LAYING"]

print("Full train:", X_train_full.shape, y_train_full.shape)
print("Full test :", X_test_full.shape, y_test_full.shape)

N_SUBSET = 3000

rng = np.random.default_rng(SEED)
idx_per_class = []
per_class_n = N_SUBSET // len(ACTIVITIES)
for c in range(len(ACTIVITIES)):
    class_idx = np.where(y_train_full == c)[0]
    chosen = rng.choice(class_idx, size=min(per_class_n, len(class_idx)), replace=False)
    idx_per_class.append(chosen)
subset_idx = np.concatenate(idx_per_class)
rng.shuffle(subset_idx)

X_pool = X_train_full[subset_idx]
y_pool = y_train_full[subset_idx]

print("Subset pool:", X_pool.shape, y_pool.shape)
print("Class distribution:", np.bincount(y_pool))

X_train, X_temp, y_train, y_temp = train_test_split(
    X_pool, y_pool, test_size=0.30, random_state=SEED, stratify=y_pool)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=SEED, stratify=y_temp)


mean = X_train.mean(axis=(0, 1), keepdims=True)
std  = X_train.std(axis=(0, 1), keepdims=True) + 1e-8

X_train_n = (X_train - mean) / std
X_val_n   = (X_val   - mean) / std
X_test_n  = (X_test  - mean) / std

print("Input tensor shape:")
print(f"  Training   : {X_train_n.shape}")
print(f"  Validation : {X_val_n.shape}")
print(f"  Testing    : {X_test_n.shape}")
print(f"Number of classes: {len(ACTIVITIES)}")
print(f"Number of features per time step: {X_train_n.shape[2]}")
print(f"Sequence length: {X_train_n.shape[1]}")

print("\nClass distribution (train):", np.bincount(y_train))
print("Class distribution (val)  :", np.bincount(y_val))
print("Class distribution (test) :", np.bincount(y_test))

def show_sensor_examples(X, y, labels, channels=("body_acc_x", "body_gyro_x", "total_acc_x"),
                         class_ids=(0, 2, 5)):
    channel_map = {name: pos for pos, name in enumerate(SIGNALS)}
    fig, axes = plt.subplots(len(class_ids), 1, figsize=(10, 8), sharex=True)
    axes = np.atleast_1d(axes)

    for ax, class_id in zip(axes, class_ids):
        candidates = np.flatnonzero(y == class_id)
        if len(candidates) == 0:
            continue
        sample = X[candidates[0]]

        for channel in channels:
            ax.plot(sample[:, channel_map[channel]], label=channel)

        ax.set_title(labels[class_id])
        ax.set_ylabel("Sensor value")
        ax.legend(loc="upper right", fontsize=8)

    axes[-1].set_xlabel("Time step (1-128)")
    plt.tight_layout()
    plt.show()

show_sensor_examples(X_train_n, y_train, ACTIVITIES)

def rnn_recurrence(sequence, initial_state, input_weight, recurrent_weight, bias):
    states = []
    state = initial_state

    for value in sequence:
        state = np.tanh(input_weight * value + recurrent_weight * state + bias)
        states.append(state)

    return states

x_seq = [0.5, 0.7, 0.2]
h0, Wx, Wh, b = 0.0, 0.5, 0.8, 0.1

manual_states = rnn_recurrence(x_seq, h0, Wx, Wh, b)
for step, state in enumerate(manual_states, 1):
    print(f"h{step} = {state:.6f}")

cell = layers.SimpleRNNCell(1, activation="tanh")
cell.build((None, 1))
cell.set_weights([
    np.asarray([[Wx]], dtype=np.float32),
    np.asarray([[Wh]], dtype=np.float32),
    np.asarray([b], dtype=np.float32)
])

state = tf.zeros((1, 1), dtype=tf.float32)

for step, value in enumerate(x_seq, 1):
    current_input = tf.convert_to_tensor([[value]], dtype=tf.float32)
    _, state_list = cell(current_input, [state])
    state = state_list[0]
    print(f"Keras h{step} = {state.numpy()[0, 0]:.6f}")

INPUT_SHAPE = (X_train_n.shape[1], X_train_n.shape[2])
NUM_CLASSES = len(ACTIVITIES)

RECURRENT_LAYERS = {
    "RNN": layers.SimpleRNN,
    "LSTM": layers.LSTM,
    "GRU": layers.GRU
}

def make_sequence_classifier(kind):
    recurrent = RECURRENT_LAYERS[kind](32)

    net = models.Sequential(name=f"{kind}_classifier")
    net.add(Input(shape=INPUT_SHAPE))
    net.add(recurrent)
    net.add(layers.Dropout(rate=0.20))
    net.add(layers.Dense(16, activation="relu"))
    net.add(layers.Dense(NUM_CLASSES, activation="softmax"))

    net.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return net

for model_name in ("RNN", "LSTM", "GRU"):
    candidate = make_sequence_classifier(model_name)
    print(f"\n{model_name}")
    candidate.summary()

EPOCHS = 30
BATCH_SIZE = 32
MODEL_ORDER = ("RNN", "LSTM", "GRU")

histories = {}
trained_models = {}
train_times = {}

for model_name in MODEL_ORDER:
    print(f"\n===== Training {model_name} =====")
    tf.random.set_seed(SEED)

    current_model = make_sequence_classifier(model_name)
    start_time = time.perf_counter()

    history = current_model.fit(
        X_train_n,
        y_train,
        validation_data=(X_val_n, y_val),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        verbose=1
    )

    elapsed = time.perf_counter() - start_time
    histories[model_name] = history
    trained_models[model_name] = current_model
    train_times[model_name] = elapsed

    print(f"{model_name} training time: {elapsed:.2f}s")

"""## 13. Required Training Plots — Loss and Accuracy Curves (Plots 2 & 3)"""

def display_training_curves(history_dict):
    fig, axes = plt.subplots(2, 3, figsize=(16, 8))

    for column, model_name in enumerate(MODEL_ORDER):
        values = history_dict[model_name].history

        axes[0, column].plot(values["loss"], label="train loss")
        axes[0, column].plot(values["val_loss"], label="val loss")
        axes[0, column].set_title(f"{model_name} — Loss")
        axes[0, column].set_xlabel("Epoch")
        axes[0, column].set_ylabel("Loss")
        axes[0, column].legend()

        axes[1, column].plot(100 * np.asarray(values["accuracy"]), label="train acc")
        axes[1, column].plot(100 * np.asarray(values["val_accuracy"]), label="val acc")
        axes[1, column].set_title(f"{model_name} — Accuracy")
        axes[1, column].set_xlabel("Epoch")
        axes[1, column].set_ylabel("Accuracy (%)")
        axes[1, column].legend()

    plt.tight_layout()
    plt.show()

display_training_curves(histories)

def trainable_parameter_count(model):
    return int(sum(tf.keras.backend.count_params(weight)
                   for weight in model.trainable_weights))

results = {}

for model_name in MODEL_ORDER:
    model = trained_models[model_name]
    probabilities = model.predict(X_test_n, verbose=0)
    predictions = np.argmax(probabilities, axis=1)

    accuracy = accuracy_score(y_test, predictions) * 100
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, predictions, average="macro", zero_division=0
    )

    results[model_name] = {
        "Accuracy (%)": accuracy,
        "Macro Precision (%)": precision * 100,
        "Macro Recall (%)": recall * 100,
        "Macro F1 (%)": f1 * 100,
        "Parameters": trainable_parameter_count(model),
        "Training Time (s)": train_times[model_name],
        "y_pred": predictions
    }

summary_df = pd.DataFrame.from_dict(
    {
        name: {key: value for key, value in metrics.items() if key != "y_pred"}
        for name, metrics in results.items()
    },
    orient="index"
)

summary_df

fig, axes = plt.subplots(1, len(MODEL_ORDER), figsize=(18, 5))

for ax, model_name in zip(axes, MODEL_ORDER):
    matrix = confusion_matrix(y_test, results[model_name]["y_pred"])
    ConfusionMatrixDisplay(
        confusion_matrix=matrix,
        display_labels=ACTIVITIES
    ).plot(ax=ax, xticks_rotation=45, colorbar=False)
    ax.set_title(model_name)

plt.tight_layout()
plt.show()

comparison_df = pd.DataFrame(
    {
        "RNN": [
            "Yes", "No", "No", "No", "No", "No", "No",
            results["RNN"]["Parameters"],
            f'{results["RNN"]["Training Time (s)"]:.2f}',
            f'{results["RNN"]["Macro F1 (%)"]:.2f}'
        ],
        "LSTM": [
            "Yes", "Yes", "Yes", "Yes", "Yes", "No", "No",
            results["LSTM"]["Parameters"],
            f'{results["LSTM"]["Training Time (s)"]:.2f}',
            f'{results["LSTM"]["Macro F1 (%)"]:.2f}'
        ],
        "GRU": [
            "Yes", "No", "No", "No", "No", "Yes", "Yes",
            results["GRU"]["Parameters"],
            f'{results["GRU"]["Training Time (s)"]:.2f}',
            f'{results["GRU"]["Macro F1 (%)"]:.2f}'
        ]
    },
    index=[
        "Hidden state", "Cell state", "Forget gate", "Input gate",
        "Output gate", "Update gate", "Reset gate", "Parameters",
        "Training time (s)", "Test F1-score (%)"
    ]
)

comparison_df

model_names = list(MODEL_ORDER)
accuracy_values = [results[name]["Accuracy (%)"] for name in model_names]
f1_values = [results[name]["Macro F1 (%)"] for name in model_names]

raw_times = np.array(
    [results[name]["Training Time (s)"] for name in model_names],
    dtype=float
)
normalized_times = 100 * raw_times / raw_times.max()

positions = np.arange(len(model_names))
bar_width = 0.25

fig, ax = plt.subplots(figsize=(8, 5))
ax.bar(positions - bar_width, accuracy_values, bar_width, label="Accuracy (%)")
ax.bar(positions, f1_values, bar_width, label="Macro F1 (%)")
ax.bar(positions + bar_width, normalized_times, bar_width,
       label="Norm. Training Time (%)")

ax.set_xticks(positions)
ax.set_xticklabels(model_names)
ax.set_ylabel("Score")
ax.set_title("Model Performance Comparison")
ax.legend()

plt.tight_layout()
plt.show()

"""## 17. Effect of Sequence Length (Plot 6)"""

def first_t_steps(X, length):
    return X[:, :length, :]

sequence_lengths = [32, 64, 128]
seqlen_results = {model_name: [] for model_name in MODEL_ORDER}

for length in sequence_lengths:
    train_part = first_t_steps(X_train_n, length)
    val_part = first_t_steps(X_val_n, length)
    test_part = first_t_steps(X_test_n, length)

    for model_name in MODEL_ORDER:
        recurrent = RECURRENT_LAYERS[model_name](32)
        experiment_model = models.Sequential([
            Input(shape=(length, X_train_n.shape[-1])),
            recurrent,
            layers.Dropout(0.2),
            layers.Dense(16, activation="relu"),
            layers.Dense(NUM_CLASSES, activation="softmax")
        ])

        experiment_model.compile(
            optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"]
        )

        experiment_model.fit(
            train_part, y_train,
            validation_data=(val_part, y_val),
            epochs=15,
            batch_size=32,
            verbose=0
        )

        predicted = np.argmax(
            experiment_model.predict(test_part, verbose=0), axis=1
        )
        _, _, macro_f1, _ = precision_recall_fscore_support(
            y_test, predicted, average="macro", zero_division=0
        )

        score = macro_f1 * 100
        seqlen_results[model_name].append(score)
        print(f"T={length:3d}  {model_name:4s}  Macro F1 = {score:.2f}%")

seqlen_df = pd.DataFrame(seqlen_results, index=sequence_lengths)
seqlen_df.index.name = "Sequence Length"
seqlen_df

plt.figure(figsize=(7, 5))

for model_name in MODEL_ORDER:
    plt.plot(
        sequence_lengths,
        seqlen_results[model_name],
        marker="o",
        label=model_name
    )

plt.xlabel("Sequence Length (T)")
plt.ylabel("Test Macro F1-score (%)")
plt.title("Sequence Length vs. Test F1-score")
plt.legend()
plt.tight_layout()
plt.show()

import cv2

SELECTED_CLASSES = ["Basketball", "Biking", "WalkingWithDog"]
UCF_DIR = "/content/UCF101_subset"
os.makedirs(UCF_DIR, exist_ok=True)






print("Expected folder layout:")
for c in SELECTED_CLASSES:
    print(f"  {UCF_DIR}/{c}/*.avi (or .mp4)")

import os, random, collections, glob, sys, builtins


if 'zip' in globals() and globals()['zip'] is not builtins.zip:
    del globals()['zip']

try:
    import remotezip as rz
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', 'remotezip'])
    import remotezip as rz
import tqdm


UCF_ZIP_URL = "https://huggingface.co/datasets/quchenyuan/UCF101-ZIP/resolve/main/UCF-101.zip"
UCF_DIR = "/content/UCF101_subset" if os.path.exists("/content") else "./UCF101_subset"
SELECTED_CLASSES = ["Basketball", "Biking", "WalkingWithDog"]
VIDEOS_PER_CLASS = 10


already_downloaded = all(
    os.path.isdir(os.path.join(UCF_DIR, cls)) and
    len(glob.glob(os.path.join(UCF_DIR, cls, "*.avi")) + glob.glob(os.path.join(UCF_DIR, cls, "*.mp4"))) >= VIDEOS_PER_CLASS
    for cls in SELECTED_CLASSES
)

if already_downloaded:
    print("UCF101 subset already downloaded and present:")
    for cls in SELECTED_CLASSES:
        cls_dir = os.path.join(UCF_DIR, cls)
        n = len(glob.glob(os.path.join(cls_dir, "*")))
        print(f"  {cls}: {n} files")
else:
    def list_files_from_zip_url(zip_url):
        with rz.RemoteZip(zip_url) as remote_zip_file:
            return [zi.filename for zi in remote_zip_file.infolist()]

    def get_class(fname):
        return fname.split('_')[-3]

    print("Fetching file list from remote zip...")
    files = [f for f in list_files_from_zip_url(UCF_ZIP_URL) if f.endswith('.avi')]

    files_for_class = collections.defaultdict(list)
    for fname in files:
        files_for_class[get_class(fname)].append(fname)

    print("Total classes available:", len(files_for_class))
    missing = [c for c in SELECTED_CLASSES if c not in files_for_class]
    if missing:
        print("Not found — pick from this list instead:", sorted(files_for_class.keys()))

    os.makedirs(UCF_DIR, exist_ok=True)
    random.seed(SEED)

    with rz.RemoteZip(UCF_ZIP_URL) as remote_zip_file:
        for cls in SELECTED_CLASSES:
            if cls not in files_for_class:
                continue
            chosen = random.sample(files_for_class[cls], min(VIDEOS_PER_CLASS, len(files_for_class[cls])))
            cls_dir = os.path.join(UCF_DIR, cls)
            os.makedirs(cls_dir, exist_ok=True)
            for fn in tqdm.tqdm(chosen, desc=cls):
                remote_zip_file.extract(fn, cls_dir)
                src_f = os.path.join(cls_dir, fn)
                dst_f = os.path.join(cls_dir, os.path.basename(fn))
                if os.path.exists(src_f):
                    if os.path.exists(dst_f) and src_f != dst_f:
                        os.remove(dst_f)
                    os.rename(src_f, dst_f)
            for root, dirs, fnames in os.walk(cls_dir, topdown=False):
                if root != cls_dir and not os.listdir(root):
                    os.rmdir(root)

    print("\nDone. Files per class:")
    for cls in SELECTED_CLASSES:
        cls_dir = os.path.join(UCF_DIR, cls)
        if os.path.isdir(cls_dir):
            print(f"  {cls}: {len(os.listdir(cls_dir))} files")

import builtins


if "zip" in globals() and globals()["zip"] is not builtins.zip:
    del globals()["zip"]

N_FRAMES = 10
IMG_SIZE = 224

mobilenet = tf.keras.applications.MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    pooling="avg",
    weights="imagenet"
)
mobilenet.trainable = False

FEATURE_DIM = int(mobilenet.output_shape[-1])
print("CNN feature dimension D =", FEATURE_DIM)

def sample_frames(video_path, frame_count=N_FRAMES):
    capture = cv2.VideoCapture(video_path)
    if not capture.isOpened():
        return None

    frames_buffer = []
    while True:
        ok, frame = capture.read()
        if not ok:
            break
        frames_buffer.append(frame)

    capture.release()

    if not frames_buffer:
        return None

    selected = np.linspace(0, len(frames_buffer) - 1, frame_count).astype(int)
    processed = []

    for frame_index in selected:
        rgb = cv2.cvtColor(frames_buffer[frame_index], cv2.COLOR_BGR2RGB)
        processed.append(cv2.resize(rgb, (IMG_SIZE, IMG_SIZE)))

    return np.asarray(processed)

def video_to_features(video_file):
    frames = sample_frames(video_file)
    if frames is None:
        return None

    batch = tf.keras.applications.mobilenet_v2.preprocess_input(
        frames.astype(np.float32)
    )
    return mobilenet.predict(batch, verbose=0)

video_paths = []
video_labels = []

for class_id, class_name in enumerate(SELECTED_CLASSES):
    folder = os.path.join(UCF_DIR, class_name)
    if not os.path.isdir(folder):
        continue

    for file_path in sorted(glob.glob(os.path.join(folder, "*"))):
        if file_path.lower().endswith((".avi", ".mp4", ".mkv")):
            video_paths.append(file_path)
            video_labels.append(class_id)

print(
    f"Found {len(video_paths)} video files across "
    f"{len(SELECTED_CLASSES)} classes."
)

feature_sequences = []
feature_labels = []

for video_file, class_id in builtins.zip(video_paths, video_labels):
    features = video_to_features(video_file)
    if features is not None:
        feature_sequences.append(features)
        feature_labels.append(class_id)

if feature_sequences:
    X_video_feats = np.stack(feature_sequences)
    y_video = np.asarray(feature_labels)

    print(
        f"Video feature tensor shape: {X_video_feats.shape}  "
        f"-> (B={X_video_feats.shape[0]}, "
        f"T={X_video_feats.shape[1]}, D={X_video_feats.shape[2]})"
    )
    print("Video labels distribution:", np.bincount(y_video))
else:
    X_video_feats = np.array([])
    y_video = np.array([], dtype=int)
    print("No videos found yet — populate the folders described above, then re-run this cell.")

if len(video_paths) > 0:
    example_frames = sample_frames(video_paths[0])

    if example_frames is not None:
        fig, axes = plt.subplots(1, N_FRAMES, figsize=(20, 3))

        for ax, frame in builtins.zip(axes, example_frames):
            ax.imshow(frame)
            ax.set_axis_off()

        plt.suptitle(
            f"Sampled frames — class: "
            f"{SELECTED_CLASSES[video_labels[0]]}"
        )
        plt.tight_layout()
        plt.show()

if len(X_video_feats) > 0:
    Xv_train, Xv_holdout, yv_train, yv_holdout = train_test_split(
        X_video_feats,
        y_video,
        test_size=0.30,
        random_state=SEED,
        stratify=y_video if len(np.unique(y_video)) > 1 else None
    )

    holdout_strata = (
        yv_holdout
        if len(np.unique(yv_holdout)) > 1 and np.min(np.bincount(yv_holdout)) >= 2
        else None
    )

    Xv_val, Xv_test, yv_val, yv_test = train_test_split(
        Xv_holdout,
        yv_holdout,
        test_size=0.50,
        random_state=SEED,
        stratify=holdout_strata
    )

    def make_video_classifier():
        network = models.Sequential([
            Input(shape=(N_FRAMES, FEATURE_DIM)),
            layers.LSTM(32),
            layers.Dense(16, activation="relu"),
            layers.Dense(len(SELECTED_CLASSES), activation="softmax")
        ], name="Video_LSTM_Model")

        network.compile(
            optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
            loss="sparse_categorical_crossentropy",
            metrics=["accuracy"]
        )
        return network

    video_model = make_video_classifier()

    video_hist = video_model.fit(
        Xv_train,
        yv_train,
        validation_data=(Xv_val, yv_val),
        epochs=20,
        batch_size=4,
        verbose=1
    )
else:
    print("Skipping training — no extracted video features available yet.")

if len(X_video_feats) > 0:
    history_values = video_hist.history

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].plot(history_values["loss"], label="train")
    axes[0].plot(history_values["val_loss"], label="val")
    axes[0].set_title("Video model — Loss")
    axes[0].legend()

    axes[1].plot(100 * np.asarray(history_values["accuracy"]), label="train")
    axes[1].plot(100 * np.asarray(history_values["val_accuracy"]), label="val")
    axes[1].set_title("Video model — Accuracy (%)")
    axes[1].legend()

    plt.tight_layout()
    plt.show()



if len(X_video_feats) > 0:
    video_probabilities = video_model.predict(Xv_test, verbose=0)
    video_predictions = np.argmax(video_probabilities, axis=1)

    video_matrix = confusion_matrix(
        yv_test,
        video_predictions,
        labels=np.arange(len(SELECTED_CLASSES))
    )

    ConfusionMatrixDisplay(
        confusion_matrix=video_matrix,
        display_labels=SELECTED_CLASSES
    ).plot(xticks_rotation=45)

    plt.title("Video — Confusion Matrix")
    plt.show()

    sample_id = 0
    predicted_id = video_predictions[sample_id]
    actual_id = yv_test[sample_id]

    print("Predicted class :", SELECTED_CLASSES[predicted_id])
    print("Actual class    :", SELECTED_CLASSES[actual_id])
    print("Confidence      :", f"{video_probabilities[sample_id, predicted_id]:.2f}")


VOCAB_SIZE = 10
SEQ_LEN = 4
N_SAMPLES = 8000
START_TOKEN = VOCAB_SIZE
END_TOKEN = VOCAB_SIZE + 1
FULL_VOCAB = VOCAB_SIZE + 2

def build_reversal_data(samples, length, vocabulary_size, seed=SEED):
    generator = np.random.default_rng(seed)
    inputs = generator.integers(
        low=0,
        high=vocabulary_size,
        size=(samples, length)
    )
    outputs = inputs[:, ::-1]
    return inputs, outputs

X_seq, Y_seq = build_reversal_data(
    N_SAMPLES, SEQ_LEN, VOCAB_SIZE
)

print("Example:", X_seq[0], "->", Y_seq[0])

start_column = np.full((N_SAMPLES, 1), START_TOKEN)
end_column = np.full((N_SAMPLES, 1), END_TOKEN)

decoder_input = np.concatenate((start_column, Y_seq), axis=1)
decoder_target = np.concatenate((Y_seq, end_column), axis=1)

split_args = dict(test_size=0.30, random_state=SEED)

(
    Xs_train, Xs_temp,
    Ys_train, Ys_temp,
    Din_train, Din_temp,
    Dtgt_train, Dtgt_temp
) = train_test_split(
    X_seq, Y_seq, decoder_input, decoder_target, **split_args
)

(
    Xs_val, Xs_test,
    Ys_val, Ys_test,
    Din_val, Din_test,
    Dtgt_val, Dtgt_temp
) = train_test_split(
    Xs_temp, Ys_temp, Din_temp, Dtgt_temp,
    test_size=0.50,
    random_state=SEED
)

print(f"Xs_train shape: {Xs_train.shape}, Din_train shape: {Din_train.shape}, Dtgt_train shape: {Dtgt_train.shape}")
print(f"Xs_val shape:   {Xs_val.shape}, Din_val shape:   {Din_val.shape}, Dtgt_val shape:   {Dtgt_val.shape}")
print(f"Xs_test shape:  {Xs_test.shape}, Din_test shape:  {Din_test.shape}, Dtgt_test shape:  {Dtgt_test.shape}")

"""### Encoder–decoder (LSTM) model"""

EMB_DIM = 16
UNITS = 64

encoder_inputs = Input(shape=(SEQ_LEN,), name="encoder_input")
encoder_embedding = layers.Embedding(FULL_VOCAB, EMB_DIM)(encoder_inputs)
_, encoder_h, encoder_c = layers.LSTM(
    UNITS, return_state=True
)(encoder_embedding)
encoder_states = [encoder_h, encoder_c]

decoder_inputs = Input(
    shape=(SEQ_LEN + 1,),
    name="decoder_input"
)
decoder_embedding_layer = layers.Embedding(FULL_VOCAB, EMB_DIM)
decoder_embedding = decoder_embedding_layer(decoder_inputs)

decoder_lstm = layers.LSTM(
    UNITS,
    return_sequences=True,
    return_state=True
)
decoder_sequence, _, _ = decoder_lstm(
    decoder_embedding,
    initial_state=encoder_states
)

decoder_output_layer = layers.Dense(
    FULL_VOCAB,
    activation="softmax"
)
decoder_sequence = decoder_output_layer(decoder_sequence)

seq2seq_model = models.Model(
    [encoder_inputs, decoder_inputs],
    decoder_sequence,
    name="seq2seq_reversal"
)

seq2seq_model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

seq2seq_model.summary()

seq2seq_hist = seq2seq_model.fit(
    x=[Xs_train, Din_train],
    y=Dtgt_train,
    validation_data=([Xs_val, Din_val], Dtgt_val),
    epochs=30,
    batch_size=64,
    verbose=1
)

"""### Inference (greedy decoding, no teacher forcing) + evaluation"""

import builtins

encoder_model = models.Model(
    encoder_inputs,
    encoder_states
)

decoder_h_input = Input(shape=(UNITS,))
decoder_c_input = Input(shape=(UNITS,))
decoder_token_input = Input(shape=(1,))

decoder_token_embedding = decoder_embedding_layer(decoder_token_input)
decoder_step_output, next_h, next_c = decoder_lstm(
    decoder_token_embedding,
    initial_state=[decoder_h_input, decoder_c_input]
)
decoder_step_output = decoder_output_layer(decoder_step_output)

decoder_model = models.Model(
    [decoder_token_input, decoder_h_input, decoder_c_input],
    [decoder_step_output, next_h, next_c]
)

def decode_sequence(input_sequence):
    states = encoder_model(
        tf.convert_to_tensor(input_sequence[None, :], dtype=tf.int32),
        training=False
    )
    hidden_state, cell_state = states

    token = tf.constant([[START_TOKEN]], dtype=tf.int32)
    generated = []

    for _ in range(SEQ_LEN):
        probabilities, hidden_state, cell_state = decoder_model(
            [token, hidden_state, cell_state],
            training=False
        )

        next_token = int(
            np.argmax(probabilities.numpy()[0, -1])
        )

        if next_token == END_TOKEN:
            break

        generated.append(next_token)
        token = tf.constant([[next_token]], dtype=tf.int32)

    return generated

correct_tokens = 0
total_tokens = 0
correct_sequences = 0
sample_rows = []

for index, source in enumerate(Xs_test):
    prediction = decode_sequence(source)
    target = list(Ys_test[index])

    padded_prediction = (prediction + [-1] * SEQ_LEN)[:SEQ_LEN]
    correct_tokens += sum(
        predicted == actual
        for predicted, actual in builtins.zip(padded_prediction, target)
    )
    total_tokens += SEQ_LEN

    if padded_prediction == target:
        correct_sequences += 1

    if index < 5:
        sample_rows.append((list(source), padded_prediction))

token_accuracy = correct_tokens / total_tokens
sequence_accuracy = correct_sequences / len(Xs_test)

print(f"Token accuracy       : {token_accuracy:.4f}")
print(f"Sequence accuracy    : {sequence_accuracy:.4f}")
print(f"Final training loss  : {seq2seq_hist.history['loss'][-1]:.4f}")
print(f"Final validation loss: {seq2seq_hist.history['val_loss'][-1]:.4f}")

print("\nSample predictions (Section 23: First 5 test examples):")
seq2seq_samples_df = pd.DataFrame(
    {
        "Input Sequence": [row[0] for row in sample_rows],
        "Predicted Output": [row[1] for row in sample_rows]
    },
    index=np.arange(1, len(sample_rows) + 1)
)
seq2seq_samples_df



consolidated = pd.DataFrame(
    {
        model_name: {
            "Accuracy": f'{results[model_name]["Accuracy (%)"]:.2f}%',
            "Precision": f'{results[model_name]["Macro Precision (%)"]:.2f}%',
            "Recall": f'{results[model_name]["Macro Recall (%)"]:.2f}%',
            "F1": f'{results[model_name]["Macro F1 (%)"]:.2f}%',
            "Parameters": results[model_name]["Parameters"]
        }
        for model_name in MODEL_ORDER
    }
).T

if len(X_video_feats) > 0:
    video_precision, video_recall, video_f1, _ = precision_recall_fscore_support(
        yv_test,
        video_predictions,
        average="macro",
        zero_division=0
    )

    consolidated.loc["CNN-LSTM/GRU"] = {
        "Accuracy": f'{accuracy_score(yv_test, video_predictions) * 100:.2f}%',
        "Precision": f'{video_precision * 100:.2f}%',
        "Recall": f'{video_recall * 100:.2f}%',
        "F1": f'{video_f1 * 100:.2f}%',
        "Parameters": trainable_parameter_count(video_model)
    }

consolidated

seq2seq_summary = pd.DataFrame(
    {
        "Metric": [
            "Token Accuracy",
            "Sequence Accuracy",
            "Final Training Loss",
            "Final Validation Loss"
        ],
        "Value": [
            f"{token_accuracy:.4f}",
            f"{sequence_accuracy:.4f}",
            f"{seq2seq_hist.history['loss'][-1]:.4f}",
            f"{seq2seq_hist.history['val_loss'][-1]:.4f}"
        ]
    }
)

