# -*- coding: utf-8 -*-
"""DLLab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDNdpQGDpVCSFbenWExscGyxnn7Yf4x6
"""

import os
import time
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from skimage.metrics import structural_similarity

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


SMOKE = os.environ.get("EXP7_SMOKE") == "1"
SEED = 42
USE_FULL_MNIST = False
N_TRAIN, N_TEST = 10_000, 2_000
BATCH = 128
EPOCHS = 20
VAE_EPOCHS = 30
LR = 1e-3
VAL_SPLIT = 0.1
LATENT_FC = 16
LATENT_VAE = 2
KL_WEIGHT = 1.0
GAUSS_SIGMAS = [0.1, 0.2, 0.3]
SP_LEVELS = [0.05, 0.10, 0.20]
TRAIN_SIGMA = 0.2
TRAIN_SP = 0.10
LATENT_DIMS = [2, 8, 16, 32]
INTERP_DIGITS = (3, 8)
OUT = "outputs_exp7"

if SMOKE:
    N_TRAIN, N_TEST, EPOCHS, VAE_EPOCHS = 300, 100, 1, 1

os.makedirs(OUT, exist_ok=True)
random.seed(SEED)
np.random.seed(SEED)
keras.utils.set_random_seed(SEED)
rng = np.random.default_rng(SEED)


def load_data():
    if SMOKE:
        r = np.random.default_rng(0)
        xtr = (r.random((N_TRAIN, 28, 28)) * 255).astype("uint8")
        xte = (r.random((N_TEST, 28, 28)) * 255).astype("uint8")
        ytr = r.integers(0, 10, N_TRAIN)
        yte = r.integers(0, 10, N_TEST)
        return xtr, ytr, xte, yte
    (xtr, ytr), (xte, yte) = keras.datasets.mnist.load_data()
    if not USE_FULL_MNIST:
        xtr, ytr = xtr[:N_TRAIN], ytr[:N_TRAIN]
        xte, yte = xte[:N_TEST], yte[:N_TEST]
    return xtr, ytr, xte, yte


x_train_raw, y_train, x_test_raw, y_test = load_data()
x_train = x_train_raw.astype("float32")[..., None] / 255.0
x_test = x_test_raw.astype("float32")[..., None] / 255.0
x_train_flat = x_train.reshape(len(x_train), 784)
x_test_flat = x_test.reshape(len(x_test), 784)
print(f"Train {x_train.shape}, Test {x_test.shape}, range [{x_train.min():.1f}, {x_train.max():.1f}]")


def recon_metrics(x, xhat):

    x = np.asarray(x, dtype="float32").reshape(-1, 28, 28)
    xhat = np.asarray(xhat, dtype="float32").reshape(-1, 28, 28)
    return {
        "MSE": float(np.mean((x - xhat) ** 2)),
        "MAE": float(np.mean(np.abs(x - xhat))),
        "SSIM": float(np.mean([structural_similarity(a, b, data_range=1.0) for a, b in zip(x, xhat)])),
    }


def per_image_error(x, xhat):

    return np.mean((x.reshape(len(x), -1) - xhat.reshape(len(xhat), -1)) ** 2, axis=1)


def save_fig(fig, name):
    fig.savefig(os.path.join(OUT, name), dpi=150, bbox_inches="tight")
    plt.show()
    plt.close(fig)


def show_rows(rows, labels, fname, n=10, title=None):

    fig, axes = plt.subplots(len(rows), n, figsize=(1.2 * n + 1.5, 1.3 * len(rows)), squeeze=False)
    for r, (imgs, lab) in enumerate(zip(rows, labels)):
        for c in range(n):
            ax = axes[r, c]
            ax.imshow(np.asarray(imgs[c]).reshape(28, 28), cmap="gray", vmin=0, vmax=1)
            ax.axis("off")
        axes[r, 0].text(-0.15, 0.5, lab, transform=axes[r, 0].transAxes, ha="right", va="center", fontsize=9)
    if title:
        fig.suptitle(title)
    save_fig(fig, fname)


def plot_history(hist, fname, title, keys=(("loss", "val_loss"),), ylabels=("Reconstruction loss",)):
    fig, axes = plt.subplots(1, len(keys), figsize=(5.5 * len(keys), 4), squeeze=False)
    for ax, (tr, va), yl in zip(axes[0], keys, ylabels):
        ax.plot(hist.history[tr], label="Training")
        ax.plot(hist.history[va], label="Validation")
        ax.set_xlabel("Epoch")
        ax.set_ylabel(yl)
        ax.legend()
        ax.grid(alpha=0.3)
    fig.suptitle(title)
    save_fig(fig, fname)


def fit_timed(model, x, y, epochs, verbose=2):
    t0 = time.time()
    hist = model.fit(x, y, epochs=epochs, batch_size=BATCH, validation_split=VAL_SPLIT,
                     shuffle=True, verbose=verbose)
    return hist, time.time() - t0


def compile_ae(model):
    model.compile(optimizer=keras.optimizers.Adam(LR), loss="binary_crossentropy")
    return model


def build_fc_ae(latent_dim=16):
    inp = keras.Input((784,))
    h = layers.Dense(128, activation="relu")(inp)
    h = layers.Dense(32, activation="relu")(h)
    z = layers.Dense(latent_dim, name="latent")(h)
    h = layers.Dense(32, activation="relu")(z)
    h = layers.Dense(128, activation="relu")(h)
    out = layers.Dense(784, activation="sigmoid")(h)
    return compile_ae(keras.Model(inp, out, name=f"fc_ae_z{latent_dim}"))


print("\n=== Fully connected autoencoder ===")
fc_ae = build_fc_ae(LATENT_FC)
fc_hist, fc_time = fit_timed(fc_ae, x_train_flat, x_train_flat, EPOCHS)
fc_recon = fc_ae.predict(x_test_flat, verbose=0)
fc_metrics = recon_metrics(x_test_flat, fc_recon)
print("FC-AE test metrics:", fc_metrics)


show_rows([x_test_flat[:10], fc_recon[:10], np.abs(x_test_flat[:10] - fc_recon[:10])],
          ["Original", "Reconstruction", "|Error|"], "plot1_fc_original_vs_recon.png",
          title="Plot 1: FC-AE, original vs reconstruction")

plot_history(fc_hist, "plot2_fc_loss_curves.png", "Plot 2: FC-AE training vs validation loss (BCE)")


def build_cae(name="cae"):
    inp = keras.Input((28, 28, 1))
    x = layers.Conv2D(32, 3, activation="relu", padding="same")(inp)
    x = layers.MaxPooling2D(2, padding="same")(x)
    x = layers.Conv2D(64, 3, activation="relu", padding="same")(x)
    x = layers.MaxPooling2D(2, padding="same")(x)
    x = layers.Conv2D(64, 3, activation="relu", padding="same")(x)
    x = layers.UpSampling2D(2)(x)
    x = layers.Conv2D(32, 3, activation="relu", padding="same")(x)
    x = layers.UpSampling2D(2)(x)
    out = layers.Conv2D(1, 3, activation="sigmoid", padding="same")(x)
    return compile_ae(keras.Model(inp, out, name=name))


print("\n=== Convolutional autoencoder ===")
cae = build_cae()
cae_hist, cae_time = fit_timed(cae, x_train, x_train, EPOCHS)
cae_recon = cae.predict(x_test, verbose=0)
cae_metrics = recon_metrics(x_test, cae_recon)
print("CAE test metrics:", cae_metrics)

comparison = pd.DataFrame([
    {"Model": "Fully Connected AE", **fc_metrics, "Parameters": fc_ae.count_params()},
    {"Model": "Convolutional AE", **cae_metrics, "Parameters": cae.count_params()},
])
print("\nFC vs CAE (same train/test images):\n", comparison.to_string(index=False))
comparison.to_csv(os.path.join(OUT, "table_fc_vs_cae.csv"), index=False)


show_rows([x_test[:10], fc_recon[:10], cae_recon[:10]], ["Original", "FC-AE", "CAE"],
          "plot3_fc_vs_cae.png", title="Plot 3: FC-AE vs CAE reconstruction")


def add_gaussian(x, sigma, r):
    return np.clip(x + r.normal(0.0, sigma, x.shape), 0.0, 1.0).astype("float32")


def add_salt_pepper(x, p, r):

    x = x.copy()
    corrupt = r.random(x.shape) < p
    salt = r.random(x.shape) < 0.5
    x[corrupt & salt] = 1.0
    x[corrupt & ~salt] = 0.0
    return x.astype("float32")


NOISES = {
    "gaussian": dict(fn=add_gaussian, levels=GAUSS_SIGMAS, train_level=TRAIN_SIGMA, label="sigma"),
    "salt_pepper": dict(fn=add_salt_pepper, levels=SP_LEVELS, train_level=TRAIN_SP, label="p"),
}

dae = {}
dae_train_time = {}
dae_hist = {}
noise_tables = {}
for kind, cfg in NOISES.items():
    print(f"\n=== Denoising CAE ({kind}, trained at {cfg['label']}={cfg['train_level']}) ===")
    model = build_cae(name=f"dae_{kind}")
    x_noisy_train = cfg["fn"](x_train, cfg["train_level"], rng)
    hist, t = fit_timed(model, x_noisy_train, x_train, EPOCHS)
    dae[kind], dae_train_time[kind], dae_hist[kind] = model, t, hist


    x_noisy_test = cfg["fn"](x_test, cfg["train_level"], rng)
    x_den = model.predict(x_noisy_test, verbose=0)
    show_rows([x_test[:10], x_noisy_test[:10], x_den[:10]], ["Clean", "Noisy", "Denoised"],
              f"plot4_denoising_{kind}.png",
              title=f"Plot 4: {kind} noise ({cfg['label']}={cfg['train_level']})")


    rows = []
    for lv in cfg["levels"]:
        noisy = cfg["fn"](x_test, lv, rng)
        den = model.predict(noisy, verbose=0)
        m_den, m_noisy = recon_metrics(x_test, den), recon_metrics(x_test, noisy)
        rows.append({"Noise level": lv, **m_den,
                     "Noisy-input MSE": m_noisy["MSE"], "Noisy-input MAE": m_noisy["MAE"],
                     "Noisy-input SSIM": m_noisy["SSIM"]})
    tbl = pd.DataFrame(rows)
    noise_tables[kind] = tbl
    print(tbl.to_string(index=False))
    tbl.to_csv(os.path.join(OUT, f"table_noise_level_{kind}.csv"), index=False)

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    for ax, metric in zip(axes, ["MSE", "MAE", "SSIM"]):
        ax.plot(tbl["Noise level"], tbl[metric], "o-", label="Denoised vs clean")
        ax.plot(tbl["Noise level"], tbl[f"Noisy-input {metric}"], "s--", label="Noisy input vs clean")
        ax.set_xlabel(f"Noise level ({cfg['label']})")
        ax.set_ylabel(metric)
        ax.grid(alpha=0.3)
        ax.legend()
    fig.suptitle(f"Plot 5: {kind}, noise level vs reconstruction quality "
                 f"(model trained at {cfg['label']}={cfg['train_level']})")
    save_fig(fig, f"plot5_noise_level_{kind}.png")

dae_main_noisy = add_gaussian(x_test, TRAIN_SIGMA, rng)
dae_main_metrics = recon_metrics(x_test, dae["gaussian"].predict(dae_main_noisy, verbose=0))


class Sampling(layers.Layer):

    def call(self, inputs):
        mu, log_var = inputs
        eps = tf.random.normal(tf.shape(mu))
        return mu + tf.exp(0.5 * log_var) * eps


def build_vae_encoder(latent_dim):
    inp = keras.Input((28, 28, 1))
    x = layers.Conv2D(32, 3, strides=2, padding="same", activation="relu")(inp)
    x = layers.Conv2D(64, 3, strides=2, padding="same", activation="relu")(x)
    x = layers.Flatten()(x)
    x = layers.Dense(16, activation="relu")(x)
    mu = layers.Dense(latent_dim, name="mu")(x)
    log_var = layers.Dense(latent_dim, name="log_var")(x)
    z = Sampling(name="z")([mu, log_var])
    return keras.Model(inp, [mu, log_var, z], name="vae_encoder")


def build_vae_decoder(latent_dim):
    inp = keras.Input((latent_dim,))
    x = layers.Dense(7 * 7 * 64, activation="relu")(inp)
    x = layers.Reshape((7, 7, 64))(x)
    x = layers.Conv2DTranspose(64, 3, strides=2, padding="same", activation="relu")(x)
    x = layers.Conv2DTranspose(32, 3, strides=2, padding="same", activation="relu")(x)
    out = layers.Conv2DTranspose(1, 3, padding="same", activation="sigmoid")(x)
    return keras.Model(inp, out, name="vae_decoder")


class VAE(keras.Model):
    def __init__(self, encoder, decoder, kl_weight=1.0, **kw):
        super().__init__(**kw)
        self.encoder, self.decoder, self.kl_weight = encoder, decoder, kl_weight
        self.total_tracker = keras.metrics.Mean(name="loss")
        self.rec_tracker = keras.metrics.Mean(name="reconstruction_loss")
        self.kl_tracker = keras.metrics.Mean(name="kl_loss")

    @property
    def metrics(self):
        return [self.total_tracker, self.rec_tracker, self.kl_tracker]

    def call(self, x):
        _, _, z = self.encoder(x)
        return self.decoder(z)

    def compute_losses(self, x):

        mu, log_var, z = self.encoder(x)
        xhat = self.decoder(z)
        rec = tf.reduce_mean(tf.reduce_sum(keras.losses.binary_crossentropy(x, xhat), axis=(1, 2)))
        kl = tf.reduce_mean(-0.5 * tf.reduce_sum(1 + log_var - tf.square(mu) - tf.exp(log_var), axis=1))
        return rec, kl

    def _update(self, rec, kl):
        total = rec + self.kl_weight * kl
        self.total_tracker.update_state(total)
        self.rec_tracker.update_state(rec)
        self.kl_tracker.update_state(kl)
        return total

    def train_step(self, data):
        x = data[0] if isinstance(data, (tuple, list)) else data
        with tf.GradientTape() as tape:
            rec, kl = self.compute_losses(x)
            total = rec + self.kl_weight * kl
        grads = tape.gradient(total, self.trainable_variables)
        self.optimizer.apply_gradients(zip(grads, self.trainable_variables))
        self._update(rec, kl)
        return {m.name: m.result() for m in self.metrics}

    def test_step(self, data):
        x = data[0] if isinstance(data, (tuple, list)) else data
        rec, kl = self.compute_losses(x)
        self._update(rec, kl)
        return {m.name: m.result() for m in self.metrics}


print("\n=== Variational autoencoder ===")
n_val = int(len(x_train) * VAL_SPLIT)
x_vae_tr, x_vae_val = x_train[:-n_val], x_train[-n_val:]
train_ds = tf.data.Dataset.from_tensor_slices(x_vae_tr).shuffle(len(x_vae_tr), seed=SEED).batch(BATCH)
val_ds = tf.data.Dataset.from_tensor_slices(x_vae_val).batch(BATCH)

encoder, decoder = build_vae_encoder(LATENT_VAE), build_vae_decoder(LATENT_VAE)
vae = VAE(encoder, decoder, kl_weight=KL_WEIGHT)
vae.compile(optimizer=keras.optimizers.Adam(LR))
t0 = time.time()
vae_hist = vae.fit(train_ds, validation_data=val_ds, epochs=VAE_EPOCHS, verbose=2)
vae_time = time.time() - t0


plot_history(vae_hist, "plot9_vae_loss_curves.png", "VAE training vs validation loss",
             keys=(("loss", "val_loss"), ("reconstruction_loss", "val_reconstruction_loss"),
                   ("kl_loss", "val_kl_loss")),
             ylabels=("Total loss", "Reconstruction loss (BCE)", "KL loss"))


rec_t, kl_t = vae.compute_losses(tf.constant(x_test))
rec_t, kl_t = float(rec_t), float(kl_t)
mu_test, logvar_test, _ = encoder.predict(x_test, verbose=0)
vae_recon = decoder.predict(mu_test, verbose=0)
vae_metrics = recon_metrics(x_test, vae_recon)
vae_params = encoder.count_params() + decoder.count_params()
vae_table = pd.DataFrame({
    "VAE Metric": ["Reconstruction Loss (BCE, per image)", "KL Loss (per image)", "Total Loss",
                   "Test MSE (z = mu)", "Test MAE (z = mu)", "Mean SSIM (z = mu)"],
    "Value": [rec_t, kl_t, rec_t + KL_WEIGHT * kl_t, vae_metrics["MSE"], vae_metrics["MAE"], vae_metrics["SSIM"]],
})
print(vae_table.to_string(index=False))
vae_table.to_csv(os.path.join(OUT, "table_vae.csv"), index=False)

show_rows([x_test[:10], vae_recon[:10], np.abs(x_test[:10] - vae_recon[:10])],
          ["Original", "VAE recon", "|Error|"], "vae_reconstruction.png", title="VAE reconstruction (z = mu)")


fig, ax = plt.subplots(figsize=(7, 6))
sc = ax.scatter(mu_test[:, 0], mu_test[:, 1], c=y_test, cmap="tab10", s=8, alpha=0.8)
cb = fig.colorbar(sc, ax=ax, ticks=range(10))
cb.set_label("Digit label")
ax.set_xlabel("z1")
ax.set_ylabel("z2")
ax.set_title("Plot 6: VAE latent space (encoder mean mu, test set)")
save_fig(fig, "plot6_vae_latent_space.png")


z_rand = np.random.normal(size=(25, LATENT_VAE)).astype("float32")
gen = decoder.predict(z_rand, verbose=0)
fig, axes = plt.subplots(5, 5, figsize=(6, 6))
for a, im in zip(axes.ravel(), gen):
    a.imshow(im.reshape(28, 28), cmap="gray", vmin=0, vmax=1)
    a.axis("off")
fig.suptitle("Plot 7: VAE samples, z ~ N(0, I)")
save_fig(fig, "plot7_vae_generated.png")


ia = int(np.where(y_test == INTERP_DIGITS[0])[0][0]) if np.any(y_test == INTERP_DIGITS[0]) else 0
ib = int(np.where(y_test == INTERP_DIGITS[1])[0][0]) if np.any(y_test == INTERP_DIGITS[1]) else 1
zA, zB = mu_test[ia], mu_test[ib]
alphas = np.linspace(0, 1, 11)
z_int = np.stack([(1 - a) * zA + a * zB for a in alphas]).astype("float32")
interp = decoder.predict(z_int, verbose=0)
fig, axes = plt.subplots(1, 11, figsize=(14, 2))
for a, im, al in zip(axes, interp, alphas):
    a.imshow(im.reshape(28, 28), cmap="gray", vmin=0, vmax=1)
    a.set_title(f"{al:.1f}", fontsize=8)
    a.axis("off")
fig.suptitle(f"Plot 8: latent interpolation, digit {y_test[ia]} -> digit {y_test[ib]} (alpha = 0 ... 1)")
save_fig(fig, "plot8_vae_interpolation.png")


print("\n=== Reconstruction error distribution ===")
for name, xin, xrec in [("FC-AE", x_test_flat, fc_recon), ("CAE", x_test, cae_recon)]:
    e = per_image_error(xin, xrec)
    print(f"{name}: mean={e.mean():.5f} median={np.median(e):.5f} std={e.std():.5f} "
          f"min={e.min():.5f} max={e.max():.5f} 95th pct={np.percentile(e, 95):.5f}")

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.hist(e, bins=50)
    ax.axvline(e.mean(), color="r", ls="--", label=f"mean = {e.mean():.4f}")
    ax.set_xlabel("Per-image reconstruction error e_i (MSE)")
    ax.set_ylabel("Number of test images")
    ax.set_title(f"Reconstruction-error distribution ({name})")
    ax.legend()
    save_fig(fig, f"plot10_error_distribution_{name.replace('-', '').lower()}.png")

    worst = np.argsort(e)[-5:][::-1]
    fig, axes = plt.subplots(2, 5, figsize=(8, 3.6))
    for c, idx in enumerate(worst):
        axes[0, c].imshow(np.asarray(xin[idx]).reshape(28, 28), cmap="gray", vmin=0, vmax=1)
        axes[0, c].set_title(f"#{c + 1} idx={idx}\ne={e[idx]:.4f}", fontsize=8)
        axes[1, c].imshow(np.asarray(xrec[idx]).reshape(28, 28), cmap="gray", vmin=0, vmax=1)
        axes[0, c].axis("off")
        axes[1, c].axis("off")
    axes[0, 0].text(-0.1, 0.5, "Original", transform=axes[0, 0].transAxes, ha="right", va="center")
    axes[1, 0].text(-0.1, 0.5, "Recon", transform=axes[1, 0].transAxes, ha="right", va="center")
    fig.suptitle(f"Five highest-error test images ({name})")
    save_fig(fig, f"high_error_top5_{name.replace('-', '').lower()}.png")


print("\n=== Latent-dimension study (FC-AE) ===")
lat_rows = []
for dz in LATENT_DIMS:
    if dz == LATENT_FC:
        m, params = fc_metrics, fc_ae.count_params()
    else:
        mdl = build_fc_ae(dz)
        mdl.fit(x_train_flat, x_train_flat, epochs=EPOCHS, batch_size=BATCH,
                validation_split=VAL_SPLIT, shuffle=True, verbose=0)
        m, params = recon_metrics(x_test_flat, mdl.predict(x_test_flat, verbose=0)), mdl.count_params()
    lat_rows.append({"Latent Dimension": dz, "MSE": m["MSE"], "SSIM": m["SSIM"], "Parameters": params})
lat_tbl = pd.DataFrame(lat_rows)
print(lat_tbl.to_string(index=False))
lat_tbl.to_csv(os.path.join(OUT, "table_latent_dim.csv"), index=False)

fig, ax = plt.subplots(figsize=(6, 4))
ax.plot(lat_tbl["Latent Dimension"], lat_tbl["MSE"], "o-")
ax.set_xscale("log", base=2)
ax.set_xticks(LATENT_DIMS)
ax.set_xticklabels(LATENT_DIMS)
ax.set_xlabel("Latent dimension")
ax.set_ylabel("Test MSE")
ax.set_title("Latent dimension vs reconstruction MSE (FC-AE)")
ax.grid(alpha=0.3)
save_fig(fig, "plot_latent_dim_vs_mse.png")


print("\n=== Consolidated results ===")
consolidated = pd.DataFrame([
    {"Model": "FC Autoencoder", **fc_metrics, "Parameters": fc_ae.count_params(), "Train time (s)": fc_time},
    {"Model": "Conv. Autoencoder", **cae_metrics, "Parameters": cae.count_params(), "Train time (s)": cae_time},
    {"Model": f"Denoising CAE (Gaussian, sigma={TRAIN_SIGMA})", **dae_main_metrics,
     "Parameters": dae["gaussian"].count_params(), "Train time (s)": dae_train_time["gaussian"]},
    {"Model": f"Denoising CAE (salt&pepper, p={TRAIN_SP})",
     **recon_metrics(x_test, dae["salt_pepper"].predict(add_salt_pepper(x_test, TRAIN_SP, rng), verbose=0)),
     "Parameters": dae["salt_pepper"].count_params(), "Train time (s)": dae_train_time["salt_pepper"]},
    {"Model": "VAE (z = mu)", **vae_metrics, "Parameters": vae_params, "Train time (s)": vae_time},
])
print(consolidated.to_string(index=False))
consolidated.to_csv(os.path.join(OUT, "table_consolidated.csv"), index=False)
print(f"\nAll figures and CSV tables saved in ./{OUT}/")